# Generated by Django 5.1.6

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug fields for existing posts"""
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.all():
        if not post.slug:
            base_slug = slugify(post.title)
            slug = base_slug
            counter = 1
            
            # Ensure unique slug
            while Post.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            post.slug = slug
            post.save()


def reverse_populate_slugs(apps, schema_editor):
    """Reverse operation - clear slugs"""
    Post = apps.get_model('blog', 'Post')
    Post.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_post_fields'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
